### ISSUE TITLE
Downloading quizzes and other content from index page

### ISSUE THREAD

**Issue by wavelink** [dgorissen/coursera-dl#86] opened 2013-08-27 09:50 UTC
Program downloaded the videos along with an index.html and lectures.html but is there a way to get the quizzes? Also the lectures.html page still has all the links pointing back to the Coursera site, would be nice if they pointed to the downloaded videos so the local content could be play from the page.

**Comment by dgorissen** [comment] 2013-08-27 16:25
duplicate of #2

**Closed as completed by dgorissen** 2013-08-27 16:25 UTC

**Comment by wavelink** [comment] 2013-08-27 21:05
Your right about the Quiz part as it would probably start a timer on some of the courses, not what you would want if taking the course real time.
