### ISSUE TITLE
Downloading download.mp4

### ISSUE THREAD

**Issue by qujiey** [dgorissen/coursera-dl#126] opened 2014-03-17 12:52 UTC
Hi,

For some reasons, it seems the script will download some files as download.mp4 filenames

**Comment by martinakos** [comment] 2014-03-17 21:33
This happens to me too.

**Comment by dgorissen** [comment] 2014-03-18 08:45
Aware of this but unfortunately not something I have the time to dig into now. If you re-download does it happen consistently? (it should not)

**Comment by Robottinosino** [comment] 2014-03-18 10:59
Happens to me too

Tino Sino

**Comment by dgorissen** [comment] 2014-03-19 10:38
this has also come up on #100 
@xu-cheng did you look into this further by any chance?

**Comment by xu-cheng** [comment] 2014-03-19 10:45
@dgorissen I think it has nothing to do with that. It relates the process to get file name.

**Comment by danmbox** [comment] 2014-03-20 15:44
For me it seems to happen when re-downloading, and only for some of the files

**Comment by pr-ravi** [comment] 2014-04-03 06:15
Happens when re - downloading, and randomly on files. Also a negative percentage is shown, eg,
status: -629145600% 68.4 KB/s

**Comment by fmjrey** [comment] 2014-05-05 12:40
I can confirm this annoying bug happens when redownloading too, and percent value is a high negative value.

**Comment by fmjrey** [comment] 2014-05-06 17:44
Just had an occurence where download.mp4 was not a duplicate of an already downloaded file.
Maybe it was because last night I had to shutdown my machine before it finished downloading, and that I started the process again today, giving me even more download.mp4 files.

**Comment by dgorissen** [comment] 2014-05-15 02:54
Again; sorry guys. I know this is an annoying issue. It came out of the port to requests away from mechanize. There is still a mechanize branch to use if this really is a problem but the branch itself is a bit outdated.

Better would be a pull request fixing this, I unfortunately no longer have the bandwidth.

**Comment by danmbox** [comment] 2014-05-15 09:43
Is there any reason at all to stick to "requests"? Was there any real problem with mechanize?

**Comment by dgorissen** [comment] 2014-05-15 10:24
This was done by @xu-cheng, resulted in python 3 compatibility and also a cleaner codebase.

**Comment by danmbox** [comment] 2014-05-15 11:08
Those are bad reasons to break functionality in _any_ project. Python3 in particular seems to have both low adoption rates and serious design flaws, see e.g. http://lucumr.pocoo.org/2014/5/12/everything-about-unicode/

I've recently had broken mp4's with HTTP headers inside, so maybe enough is enough. I'm surprised you accepted @xu-cheng's changes so easily on the trunk in fact when so many questions remained unanswered and even you noticed broken DLs in #100

**Comment by xu-cheng** [comment] 2014-05-15 11:39
@danmbox all of these problems are NOT the result of using requests. The problem comes from coursera's end. At the time of my pull requests are merged, it works fine. The reason that moving to requests is essential is that mechanize has seized developing (last changed is two years ago with lots of unsolved issues) and python 3 support. Sorry, I don't agree in your opinion in Python 3. In fact Python 3 has lots of design advantages over Python 2, if you were really looking into the tech details. As the low adoption, it's the old story. As you should know, there will no be a Python 2.8. Python 2.7 is the end. And most of important Python packages have moved to Python 3. Fedora and other linux distro have set Python 3 as default Python interpreter. In addition, Python 3's unicode support is an important factor here when you deal with non-English coursera classes.

@dgorissen to solve all of these once for all, I suggest that we drop filename from HTTP header. Instead, we name the file from what we get in index.html. Therefore, it will have no naming issue, better support for Windows path length limitation and can be a huge help to connection robust. (Current problem mainly comes from GET method to get file name). If it's ok to you, I will do these in my free time, and do some experiments to check any changes from coursera's end.

**Comment by danmbox** [comment] 2014-05-15 12:14
@xu-cheng the main problem is **not the borked filenames**, it's the broken **file contents**. I see HTTP headers inside files! I also see files that seem put together from chunks in the wrong order (PDF starts with 2nd half of the original file, then HTTP headers, then the 1st half).

Have you looked at what requests does under the hood? It even has its own connection pool. Perhaps setting some parameters to "safe" values would work better (e.g. single connection, close after each download)?

Alternatively, perhaps mechanize works well enough that it doesn't need major changes? Maybe we can have a simple abstraction layer if requests isn't up to the job yet, but will be in the future?

As far as py3, my point was that sacrificing functionality for python3 compatibility is a bad idea. I don't want to start flamewar, but Is there anything unicode-related that py2 cannot handle? Python3 tries to force unicode strings everywhere, even though some things are naturally byte arrays with no clear encoding -- e.g. in UNIX filenames (the same mistake that Java made a while ago). That's what the rant I linked to was highlighting (read the python3 cat example to see what writing a correct application involves; of course it's easy to write buggy apps that frustrate users).

**Comment by xu-cheng** [comment] 2014-05-15 12:48
@danmbox Of course, I look deep into what requests does. The problem of broken file contents is the result of strange connection of coursera's end. And part of it is the result of current filename getting method. Now the code would try to get file name first through HTTP header. And coursera's server wouldn't return filename by HEAD method, so the code (both requests and mechanize) uses GET method to get filename.  But still sometimes coursera doesn't return the right filename. And as the result of GET method, after we get the header, we close the connection. Somehow these manually closed GET connection will make the further coursera connection unstable. I suspect that couresra has some anti-batch download policy.

As for unicode,  mechanize doesn't handle very well.

**Comment by danmbox** [comment] 2014-05-15 14:29
So can you configure requests to _not_ perform double-GETs (and use the filename from index.html)? And would that make the connections more "stable" (i.e. no chunks in wrong order, no HTTP headers in files)?

"unicode, mechanize doesn't handle very well" -- is this about file contents or file name? Again, you could use the file name from index.html.

**Comment by xu-cheng** [comment] 2014-05-15 14:31
That's exactly what I am going to do.

**Comment by danmbox** [comment] 2014-05-22 16:26
I see zero problems from mechanize branch, in recent testing. I have a script that checks for broken videos, PDFs containing HTTP headers, empty files (all the goodies that came along with requests).

**Comment by vikasbucha** [comment] 2014-06-26 09:55
I had the exact same problem.
submitted a pull request for quick fix.

**Comment by nick-s-b** [comment] 2014-08-02 01:58
Is there a fix yet? This bug has rendered coursera-dl completely useless to be. It happens ALL the time. So annoying.

**Comment by danmbox** [comment] 2014-08-02 04:31
Use the mechanize branch, it works perfectly.

@dgorissen, would it make sense to make mechanize the default branch? @xu-cheng has disappeared after destroying coursera-dl.

**Comment by xu-cheng** [comment] 2014-08-02 04:45
I'm not disappeared. I'm just extreme preoccupy and busy.

**Comment by dgorissen** [comment] 2014-08-04 16:39
Have set the default branch in github to mechanize. Will update the package in pip as well. It is behind a number of commits though. @danmbox would appreciate it if you could have a look at those, port over the ones you think are important, and issue a PR.

**Comment by dgorissen** [comment] 2014-08-04 22:11
Ok, I found some time and backported a number of commits from master to mechanize & bumped the version. Please test. If I hear no complaints I will update the package on pypi

**Comment by dgorissen** [comment] 2014-08-06 09:39
Package updated on pypi. Will close this issue. Feel free to reopen if anybody wants to tackle this on the 2.x master branch.

**Closed as completed by dgorissen** 2014-08-06 09:39 UTC
