### ISSUE TITLE
Failed to authenticate.

### ISSUE THREAD

**Issue by divijkumar** [dgorissen/coursera-dl#171] opened 2014-12-23 09:46 UTC
Seems very similar to: 
https://github.com/dgorissen/coursera-dl/issues/137

I am seeing this issue again. I have verified that the coursera-dl, beautifulsoup4, mechanize & argparse are all updated and are at the latest versions. Am running on mac osx 10.9.5, python 2.7.5.

Coursera-dl v3.1 (html.parser)
Logging in as 'xyz@abc.com'...
Traceback (most recent call last):
File "/usr/local/bin/coursera-dl", line 8, in 
load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 649, in main
d.login(args.course_names[0])
File "/Library/Python/2.7/site-packages/courseradownloader/courseradownloader.py", line 168, in login
raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as xyz@abc.com

**Comment by dgorissen** [comment] 2014-12-24 12:35
Duplicate of #164

**Closed as completed by dgorissen** 2014-12-24 12:35 UTC
