### ISSUE TITLE
Cant download old courses

### ISSUE THREAD

**Issue by ankitml** [dgorissen/coursera-dl#72] opened 2013-08-23 08:51 UTC
eg. with https://class.coursera.org/progfun-2012-001/lecture/index

even after accepting honor code, I get exception,

" Warning: no downloadable content found for progfun-2012-001, did you accept the honour code?
"

**Comment by seanhandley** [comment] 2013-08-23 11:05
I get the same problem with https://class.coursera.org/intropsych-001

**Comment by seanhandley** [comment] 2013-08-23 11:29
This is a duplicate of #71

**Comment by dgorissen** [comment] 2013-08-23 15:11
duplicate of #69

**Closed as completed by dgorissen** 2013-08-23 15:11 UTC
