### ISSUE TITLE
Course gets 404 from script, works in browser

### ISSUE THREAD

**Issue by Solsmed** [dgorissen/coursera-dl#53] opened 2013-06-08 21:37 UTC
I got this problem in both current version and the one before that.
For the course **bluebrain-001**, I get the following error spat back at me. I am able to view and download the material through a browser. All other courses (a handful) that I've tried so far have worked.

Running from linux.

**coursera-dl -u xxxxxxxxxxxx@xxxxxxxx -p xxxxxxxxxxxxx bluebrain-001**
 Warning: lxml not available, falling back to built-in 'html.parser' (see -q option), this may cause problems on Python < 2.7.3
Coursera-dl v1.4.8 (html.parser)
Logging in as 'xxxxxxx@xxxxxxxxx'...

Course 1 of 1
. Collecting downloadable content from https://class.coursera.org/bluebrain-001/lecture/index
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 598, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 301, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/usr/local/lib/python2.6/dist-packages/courseradownloader/courseradownloader.py", line 212, in get_downloadable_content
    pg = self.browser.open(lurl,timeout=self.TIMEOUT)
  File "/usr/local/lib/python2.6/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.6/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by dgorissen** [comment] 2013-06-11 16:42
duplicate of issue #51

**Closed as completed by dgorissen** 2013-06-11 16:42 UTC
