### ISSUE TITLE
Failed to authenticate - Coursera-dl 3.1

### ISSUE THREAD

**Issue by aimlnerd** [dgorissen/coursera-dl#165] opened 2014-12-20 01:54 UTC
When i run coursera-dl 3.1 i am getting below error message.
Exception: failed to authenticate as xyz@gmail.com

But i am able to login to coursera.com using the same credentials. We tried with my friends credentials also, still not working. Please advice.

**Comment by dgorissen** [comment] 2014-12-20 23:42
Duplicate of #164

**Closed as completed by dgorissen** 2014-12-20 23:42 UTC
