### ISSUE TITLE
Unable to download archived course

### ISSUE THREAD

**Issue by agroferia** [dgorissen/coursera-dl#38] opened 2013-04-13 09:27 UTC
Hi! Thanks for the program! I tried to download an archived course, specifically: Computer Architecture by David Wentzlaff. Code name: comparch-2012-001. 

![image](https://f.cloud.github.com/assets/4144360/376297/36eff9c2-a41c-11e2-9965-c9dd64b3c13d.png)

That's the error that gave me (Course 12 of 12). Sorry I don't know how to copy the text log!

**Comment by dgorissen** [comment] 2013-04-13 10:33
I did not get this error but did find another subtle problem. Please upgrade and try again.

**Comment by dgorissen** [comment] 2013-04-20 14:20
No reply so assuming ok, closing.

**Comment by rmchiriac** [comment] 2013-05-05 22:17
Same issue here, but on linux. After a bit of debugging turned out that lxml wasn't parsing properly the page content. Could be related to the fact that I viewed some lessons on coursera's site?

Anyhow, switched to html5lib and it worked.

Cheers,
Radu

**Comment by dgorissen** [comment] 2013-05-06 09:01
Mmm strange, I couldn't reproduce it, reopening.

**Comment by rmchiriac** [comment] 2013-05-06 10:50
It's not a coursera-dl issue: I've checked the html downloaded from coursera - seemed ok (even validated it with validator.w3.org). It's lxml... With the coursera-dl patched to use html5lib I've downloaded ~30 courses for later viewing w/o any issue.

**Comment by dgorissen** [comment] 2013-05-28 16:35
had another look, I have not run into these issues but if switching to html5lib works (you can use the -q option) then thats fine and I will close this.

**Closed as completed by dgorissen** 2013-05-28 16:35 UTC
