### ISSUE TITLE
 Failed to authenticate

### ISSUE THREAD

**Issue by poluekt** [dgorissen/coursera-dl#170] opened 2014-12-22 18:41 UTC
Using latest coursera-dl script, started getting authentication error about a week ago.

C:\Windows\System32>coursera-dl -u name@gmail.com -p pass -d c:\temp procmin-001
Coursera-dl v3.1 (html.parser)
Logging in as 'name@gmail.com'...
Traceback (most recent call last):
  File "C:\Python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py", line 649, in main
    d.login(args.course_names[0])
  File "C:\Python27\lib\site-packages\courseradownloader\courseradownloader.py", line 168, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as name@gmail.com

**Comment by dgorissen** [comment] 2014-12-22 20:54
duplicate of #164

**Closed as completed by dgorissen** 2014-12-22 20:54 UTC
