### ISSUE TITLE
Problem to download data

### ISSUE THREAD

**Issue by marcoberri** [dgorissen/coursera-dl#51] opened 2013-06-03 16:19 UTC
When i try download:

berri@nbberri:~/coursera$ sudo coursera-dl -d /home/berri/coursera/ bluebrain-001
Coursera-dl v1.4.8 (lxml)
Credentials found in .netrc file
Logging in as 'marcoberri@gmail.com'...

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/bluebrain-001/lecture/index
  Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 598, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 301, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 212, in get_downloadable_content
    pg = self.browser.open(lurl,timeout=self.TIMEOUT)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
  mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by dgorissen** [comment] 2013-06-08 14:11
Can you confirm this happens with the latest version from github and with a different parser (try lxml and html.parser)

**Comment by marcoberri** [comment] 2013-06-11 16:47
yes, when try with other  parser?

berri@nbberri:/home/marco/coursera$ coursera-dl bluebrain-001
Coursera-dl v1.4.8 (lxml)
Credentials found in .netrc file
Logging in as 'marcoberri@gmail.com'...

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/bluebrain-001/lecture/index
  Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.4.8', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 598, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 301, in download_course
    (weeklyTopics, allClasses) = self.get_downloadable_content(course_url)
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 212, in get_downloadable_content
    pg = self.browser.open(lurl,timeout=self.TIMEOUT)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
  mechanize._response.httperror_seek_wrapper: HTTP Error 404: Not Found

**Comment by dgorissen** [comment] 2013-06-13 16:57
a quick test with the version in github shows that it works for me, albeit with a few warnings. I need to doublecheck where they come from but otherwise it seemed to work.

**Comment by dgorissen** [comment] 2013-06-15 07:16
doublechecked, all works as expected with the current master branch, closing.

**Comment by anadi** [comment] 2013-09-25 09:01
Very cool tool. Congrats dgorissen. In some courses I also see this problem. I installed the application using this command on ubuntu 12.04:
sudo pip install coursera-dl
Does that ensure that I have the latest code with me? Alternately, how can I build the app from code? I dont know much python, some direction on this will help me a ton.

Thanks in advance.

**Comment by dgorissen** [comment] 2013-09-25 16:08
To ensure you have the latest version install with "sudo pip install
--upgrade coursera-dl". Current version is 1.5. If you have problems with
that version please paste the full log.

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by anadi** [comment] 2013-09-29 09:20
Hi Dirk,
I did the upgrade. 

I downloaded many courses. coursera-dl worked for a majority of courses that I signed up for. Other two it didn't work are these:
gametheory-2012-002
images-2012-001
neuralnets-2012-001

Few that worked:
mathphil-001
programming2-001
algo-004

Common among all the courses that did not download is that they end in 2012-001. Maybe that will make your investigation easier.

The problem persists, the log follows:
coursera-dl -d courses/ neuralnets-2012-001
Coursera-dl v1.5 (html.parser)
Credentials found in .netrc file
Logging in as 'xxxx@xxx.com'...

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/neuralnets-2012-001/lecture/index
- Got all downloadable content for neuralnets-2012-001
- neuralnets-2012-001 will be downloaded to /home/anadi/courses/neuralnets-2012-001
  - Downloading lecture/syllabus pages
    Traceback (most recent call last):
    File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==1.5', 'console_scripts', 'coursera-dl')()
    File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 564, in main
    d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
    File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 386, in download_course
    self.download_about(cname,course_dir)
    File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 342, in download_about
    about_json = self.browser.open(about_url,timeout=self.TIMEOUT).read()
    File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
    File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
    mechanize._response.httperror_seek_wrapper: HTTP Error 404: NOT FOUND

**Comment by anadi** [comment] 2013-09-29 17:26
The problem is with courseradownloader.py line 338:
base_name = cname[:cname.rindex('-')]
It translates base name to:
neuralnets-2012
while it should be 
neuralnets

For the courses I mentioned, just changing rindex to index worked for me. Now, this hack will work only for the courses that do not have a - in the name. I guess neuralnets-2012-001 is the past version of the course.

**Comment by dgorissen** [comment] 2013-10-01 21:05
will have a look at this

**Comment by dgorissen** [comment] 2013-10-01 21:05
Hi Anadi,

Thanks. Glad its helpful. You can donate something if you wish, it will
help me support the tool. I have added a donate button here
http://dirkgorissen.com/2012/09/07/coursera-dl-a-coursera-download-script/

Cheers
Dirk

---

Web / Blog : http://dirkgorissen.com
Twitter       : https://twitter.com/elazungu

**Comment by dgorissen** [comment] 2013-10-05 15:33
just tried with neuralnets, the current master version works fine for me.

**Closed as completed by dgorissen** 2013-10-05 15:33 UTC
