### ISSUE TITLE
Does not accept password with special characters

### ISSUE THREAD

**Issue by hanxue** [dgorissen/coursera-dl#92] opened 2013-09-01 04:33 UTC
I am using a coursera password with the character '^' and **coursera-dl** keeps showing **Exception: Invalid username and password**. Logging in via the website directly works fine. 

Workaround: change password to alphanumerical string without special characters. 

Python: 2.7.2
OS: Windows 7 64bit

**Comment by ghost** [comment] 2013-09-01 06:13
duplicate of issue https://github.com/dgorissen/coursera-dl/issues/82

**Closed as completed** 2013-09-01 09:29 UTC
