### ISSUE TITLE
Failed to authenticate coursera-dl

### ISSUE THREAD

**Issue by Drago1987** [dgorissen/coursera-dl#168] opened 2014-12-21 12:19 UTC
I am working with ubuntu and have the following error when trying to download videos with the coursera-dl tool:

Coursera-dl v3.1 (html.parser)
Logging in as 'myname@mymail.com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 649, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 168, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as myname@mymail.com

I also updated the tool as recommended by the post ''Failed to authenticate #147'' 
Any suggestions?
Thanks in advance

**Comment by Stanpol** [comment] 2014-12-21 17:20
You can use version 2.0.2 before this issue is fixed. 

pip uninstall coursera-dl
pip install coursera-dl==2.0.2

Version 2.0.2 works without any problems.

**Comment by dgorissen** [comment] 2014-12-21 21:06
duplicate of #164

**Closed as completed by dgorissen** 2014-12-21 21:06 UTC
