### ISSUE TITLE
index.html and lectures.html are broken

### ISSUE THREAD

**Issue by SebastianLopienski** [dgorissen/coursera-dl#157] opened 2014-11-03 21:44 UTC
After downloading course materials, when I open index.html or lectures.html with any browser, I see this error instead of the expected content (e.g. the list of lectures):

```
ooops... HTTP 404
Looks like you found a page that does not exist or the URL was mistyped by accident.
If you feel this was an error, please visit our help site to contact us.
```

(Tried on several different courses, and with different browsers)

**Comment by dgorissen** [comment] 2014-11-03 22:39
duplicate of #121 

This is simply because the html files are not modified to point to the local files.

**Closed as completed by dgorissen** 2014-11-03 22:40 UTC

**Comment by SebastianLopienski** [comment] 2014-11-04 22:45
Sure, the downloaded html files indeed don't point to the local resource files. But they don't even include a list of lectures. I guess these html files are inherently broken because of how the original Coursera pages are dynamically built. Instead of trying to solve it (and risking that any solution breaks as soon as Coursera changes something on their side), I thought of simply generating an additional html file with a list of lectures and their resources. Here's one possible implementation: #158 - thanks for considering it.

**Comment by dgorissen** [comment] 2014-11-06 21:11
Agreed. Traveling now, will look at the PR, feel free to poke if  you haven't heard back in a while.

**Comment by SebastianLopienski** [comment] 2014-11-18 21:54
Just a gentle reminder poke :-) have you had a chance to look at it?
