### ISSUE TITLE
Gets: "no downloadable content found"

### ISSUE THREAD

**Issue by lajlev** [dgorissen/coursera-dl#71] opened 2013-08-23 08:49 UTC
I have paticipated in several courses and have fill out the code of honor.

Any clue what does wrong?

```
[~/Des...top/coursera-dl] $ coursera-dl -u my@email.com -p mypassword -d /Users/lajlev/Desktop/coursera-dl/ socialpsychology-001
 Warning: built-in 'html.parser' may cause problems on Python < 2.7.3
Coursera-dl v1.4.10 (html.parser)
Logging in as 'lajlev@gmail.com'...

Course 1 of 1
* Collecting downloadable content from https://class.coursera.org/socialpsychology-001/lecture/index
 Warning: no downloadable content found for socialpsychology-001, did you accept the honour code?

```

**Comment by Autumn-Atlas** [comment] 2013-08-23 08:51
Same problem for scigast-001, and matrix-001.

**Comment by mishari** [comment] 2013-08-23 09:45
Having the same issue for socialpsychology

**Comment by radugrosu** [comment] 2013-08-23 13:36
same for matrix-001

**Comment by dgorissen** [comment] 2013-08-23 15:11
duplicate of #69

**Closed as completed by dgorissen** 2013-08-23 15:11 UTC
