### ISSUE TITLE
Lectures for matrix-001 not downloaded

### ISSUE THREAD

**Issue by jaskerr** [dgorissen/coursera-dl#73] opened 2013-08-23 15:37 UTC
The script finds no downloadable content. I accepted the honor code weeks ago, when the course began.

The coursename is correct, and the URL coursera-dl uses is also correct.

Help?

(OS X 10.6.8, python 2.7.5 [via homebrew])

Output:

> $ coursera-dl -u username -p password -d ~/Documents/Coursera/ matrix-001
> Coursera-dl v1.4.10 (html.parser)
> Logging in as 'username'...
> 
> Course 1 of 1
> - Collecting downloadable content from https://class.coursera.org/matrix-001/lecture/index  
>   Warning: no downloadable content found for matrix-001, did you accept the honour code?

**Comment by dgorissen** [comment] 2013-08-23 17:02
Duplicate of #69

**Closed as completed** 2013-08-23 18:31 UTC

**Comment by jaskerr** [comment] 2013-08-23 18:33
Got it. Thanks.
