### ISSUE TITLE
possibility to download previews

### ISSUE THREAD

**Issue by koen-dejonghe** [dgorissen/coursera-dl#11] opened 2012-12-26 07:08 UTC
Some of the courses have previews, for example https://class.coursera.org/nlp/lecture/preview.
Is it possible to adapt the script so that it can download the previews as well ?
Cheers.

**Comment by dgorissen** [comment] 2013-01-04 17:08
This could be done I guess but its not something I have time for at the moment Im afraid :/

**Comment by dgorissen** [comment] 2013-03-18 11:41
duplicate of #10

**Closed as completed by dgorissen** 2013-03-18 11:41 UTC
Labels: duplicate
