### ISSUE TITLE
Failed to Authenticate

### ISSUE THREAD

**Issue by zjllee** [dgorissen/coursera-dl#167] opened 2014-12-21 02:21 UTC
C:\Apps\Python27\Scripts>coursera-dl -u ****_@gmail.com -p ***_**\* -d D:\Course
 -w 7 procmin-001
Traceback (most recent call last):
  File "C:\Apps\Python27\Scripts\coursera-dl-script.py", line 9, in <module>
    load_entry_point('coursera-dl==3.1', 'console_scripts', 'coursera-dl')()
  File "C:\Apps\Python27\lib\site-packages\courseradownloader\courseradownloader
.py", line 649, in main
    d.login(args.course_names[0])
  File "C:\Apps\Python27\lib\site-packages\courseradownloader\courseradownloader
.py", line 168, in login
    raise Exception("Failed to authenticate as %s" % self.username)
Exception: Failed to authenticate as ******@gmail.com

It was working just last week. I wonder what is wrong with it. Thank you for your help!

**Comment by clampak** [comment] 2014-12-21 02:24
I have this same issue.

**Comment by milkfan** [comment] 2014-12-21 06:39
I have this same issue.
Already merged code with pull-request #166

**Comment by dgorissen** [comment] 2014-12-21 21:05
@milkfan can you confirm the problem persists with the current master?

**Comment by milkfan** [comment] 2014-12-22 00:06
@dgorissen I was on the branch mechanize. Confirm it's not working with the latest coursera-dl. Am I supposed to switch to the master?

**Comment by milkfan** [comment] 2014-12-22 00:11
@dgorissen The master branch has not been updated for a while now, right? It's not working on either master or mechanize. However, as someone pointed out in issue #164, I can install coursera-dl==2.0.2 instead and it works fine for me.

**Comment by dgorissen** [comment] 2014-12-22 00:20
Sorry I meant mechanize branch.

**Comment by colablikje** [comment] 2014-12-22 21:35
I have the same issue. Are you suggesting to replace courseradownloader.py from the mechanize branch? I did that, but that isn't working either. 
(I don't want to steal the threat, just add that this is an issue that concerns more people)

**Comment by poluekt** [comment] 2014-12-22 21:39
I don't think @danmbox verified the fix.

**Comment by donalddominko** [comment] 2014-12-22 22:40
Working on Ubuntu 12.04 and I have the same issue. Not sure but did I merge everything as I should? This is how my folder looks now:

Dec 22 23:18 CHANGELOG.txt
Oct 30 20:54 CONTRIBUTING.md
Oct 30 21:08 coursera
Oct 30 20:54 coursera-dl
Oct 30 20:54 coursera-dl.bat
Dec 22 23:18 courseradownloader
Dec 22 23:18 LICENSE.txt
Dec 22 23:18 MANIFEST.in
Dec 22 23:18 README.md
Dec 22 23:18 requirements.txt
Dec 22 23:18 setup.py

As I understand @danmbox has to do the verification and then simple " git fetch https://github.com/dgorissen/coursera-dl" will do the trick?

**Comment by danmbox** [comment] 2014-12-23 13:21
The current mechanize branch in this repository seems to WFM:

> cd /tmp
> $ git clone git://github.com/dgorissen/coursera-dl.git
> $ cd coursera-dl
> $ git branch 
>   mechanize
> $ python courseradownloader/courseradownloader.py -u $USER -p $PASS healthliteracy-001

Does this work?

**Comment by poluekt** [comment] 2014-12-23 15:32
worked for me. 
I had to download new version directly from the github web site. Is there a way to do it with pip?

**Comment by danmbox** [comment] 2014-12-23 15:35
If the maintainer decides to bump the version and release to pypy...

**Comment by donalddominko** [comment] 2014-12-23 17:53
I tried your version and had partial success. Did some download and then it hang so I did CTRL+C .. I'm posting entire output in case someone wants to reproduce and debug.

~/Documents/Workspace/Coursera.com/Data-Scientist-Specialization/Regression-Models$ python /tmp/coursera-dl/courseradownloader/courseradownloader.py -u USERNAME -p PASSWORD regmods-016
Coursera-dl v3.1 (html.parser)
Logging in as 'USERNAME'...

Course 1 of 1
- Collecting downloadable content from https://class.coursera.org/regmods-016/lecture/index
- Got all downloadable content for regmods-016
- regmods-016 will be downloaded to /home/donald/Documents/Workspace/Coursera.com/Data-Scientist-Specialization/Regression-Models/regmods-016
  - Downloading lecture/syllabus pages
    Warning: failed to download about file HTTP Error 400: Bad Request
  - Week 1
  - Downloading resources for 01_01_a Introduction to regression (4-10)
    - Downloading  https://github.com/bcaffo/courses/blob/master/07_RegressionModels/pdfs/01_01.pdf?raw=true None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=135_en&format=txt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=135_en&format=srt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/download.mp4?lecture_id=135 None
  - Downloading resources for 01_01_b Basic least squares (5-41)
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=137_en&format=txt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=137_en&format=srt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/download.mp4?lecture_id=137 None
  - Downloading resources for 01_01_c Least squares continued (5-38)
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=139_en&format=txt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=139_en&format=srt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/download.mp4?lecture_id=139 None
  - Downloading resources for 01_01_d Regression through the origin (7-37)
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=141_en&format=txt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=141_en&format=srt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/download.mp4?lecture_id=141 None
  - Downloading resources for 01_02_a Basic Notation and Background (3-26)
    - Downloading  https://github.com/bcaffo/courses/blob/master/07_RegressionModels/pdfs/01_02.pdf?raw=true None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=143_en&format=txt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/subtitles?q=143_en&format=srt None
    - Downloading  https://class.coursera.org/regmods-016/lecture/download.mp4?lecture_id=143 None
      ^CTraceback (most recent call last):
      File "/tmp/coursera-dl/courseradownloader/courseradownloader.py", line 657, in <module>
      main()
      File "/tmp/coursera-dl/courseradownloader/courseradownloader.py", line 654, in main
      d.download_course(cn,dest_dir=args.dest_dir,reverse_sections=args.reverse,gzip_courses = args.gzip_courses)
      File "/tmp/coursera-dl/courseradownloader/courseradownloader.py", line 493, in download_course
      class_dir=path.join(wkdirname, clsdirname))
      File "/tmp/coursera-dl/courseradownloader/courseradownloader.py", line 389, in download
      self.browser.retrieve(url,filepath,timeout=self.TIMEOUT)
      File "/usr/local/lib/python2.7/dist-packages/mechanize/_opener.py", line 277, in retrieve
      block = fp.read(bs)
      File "/usr/local/lib/python2.7/dist-packages/mechanize/_response.py", line 195, in read
      data = self.wrapped.read(to_read)
      File "/usr/lib/python2.7/socket.py", line 380, in read
      data = self._sock.recv(left)
      File "/usr/lib/python2.7/httplib.py", line 561, in read
      s = self.fp.read(amt)
      File "/usr/lib/python2.7/socket.py", line 380, in read
      data = self._sock.recv(left)
      File "/usr/lib/python2.7/ssl.py", line 241, in recv
      return self.read(buflen)
      File "/usr/lib/python2.7/ssl.py", line 160, in read
      return self._sslobj.read(len)
      KeyboardInterrupt

**Comment by danmbox** [comment] 2014-12-23 20:50
Yeah, that used to happen every once in a while (on both branches I believe). Ctrl-C and re-download, possibly using the week filter to avoid checking perfectly fine videos.

**Comment by dgorissen** [comment] 2014-12-24 12:34
Verified and @danmbox 's PR #164 works for me. Bumped coursera version on pypi.

**Closed as completed by dgorissen** 2014-12-24 12:34 UTC
